services:
  backend:
    build:
      context: ./backend
    container_name: fitfolio-backend
    working_dir: /workspaces/fitfolio/backend
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /workspaces/fitfolio/backend
    volumes:
      - ./:/workspaces/fitfolio:cached
      - sshkeys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      EMAIL_SENDER: ${EMAIL_SENDER}
      JWT_SECRET: ${JWT_SECRET}
      PYTHONPATH: /workspaces/fitfolio
      LOG_LEVEL: info
      OTEL_SERVICE_NAME: fitfolio-backend
      # Updated CORS for Traefik domain
      CORS_ORIGINS: https://fitfolio.dev.rutabagel.com,http://localhost:5173
      # OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318/v1/traces   # enable if you run an OTLP collector (e.g., Tempo/Jaeger/Otel-collector)
    ports:
      - "8080:8000"  # Keep for direct access during dev
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Traefik integration
    labels:
      - "traefik.enable=true"
      # Router for API endpoints - higher priority to match /api paths first
      - "traefik.http.routers.fitfolio-backend.rule=Host(`fitfolio.dev.rutabagel.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fitfolio-backend.entrypoints=websecure"
      - "traefik.http.routers.fitfolio-backend.tls=true"
      - "traefik.http.routers.fitfolio-backend.priority=10"
      # Service config (backend runs on port 8000 internally)
      - "traefik.http.services.fitfolio-backend.loadbalancer.server.port=8000"
    networks:
      - traefik-public  # For Traefik routing
      - default         # For internal service communication


  frontend:
    build:
      context: ./frontend
    container_name: fitfolio-frontend
    working_dir: /workspaces/fitfolio/frontend
    command: ["sh", "-lc", "npm ci && npm run dev -- --host"]
    volumes:
      - ./:/workspaces/fitfolio:cached
      - /workspaces/fitfolio/frontend/node_modules
    ports:
      - "5173:5173"  # Keep for direct access during dev
    environment:
      - NODE_ENV=development
      # Vite proxy will still work for internal container communication
      - VITE_API_TARGET=http://backend:8000
      # Allowed host for Vite dev server
      - VITE_ALLOWED_HOST=fitfolio.dev.rutabagel.com
    stdin_open: true
    tty: true
    depends_on:
      - backend
    # Traefik integration
    labels:
      - "traefik.enable=true"
      # Router for frontend - lower priority catches all non-API paths
      - "traefik.http.routers.fitfolio-frontend.rule=Host(`fitfolio.dev.rutabagel.com`)"
      - "traefik.http.routers.fitfolio-frontend.entrypoints=websecure"
      - "traefik.http.routers.fitfolio-frontend.tls=true"
      - "traefik.http.routers.fitfolio-frontend.priority=1"
      # Service config (Vite dev server runs on port 5173 internally)
      - "traefik.http.services.fitfolio-frontend.loadbalancer.server.port=5173"
    networks:
      - traefik-public  # For Traefik routing
      - default         # For internal service communication

  db:
    image: postgres:16
    container_name: fitfolio-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 20

  mail:
    image: axllent/mailpit:latest
    container_name: fitfolio-mail
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fitfolio-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped


networks:
  traefik-public:
    external: true  # Connects to external Traefik network
  default:
    driver: bridge  # Internal network for service-to-service communication

volumes:
  pgdata:
  redisdata:
  sshkeys:
