# compose.prod.yml
services:
  backend:
    image: fitfolio-backend:prod
    container_name: fitfolio-backend-prod
    env_file: .env
    environment:
      LOG_LEVEL: info
      OTEL_SERVICE_NAME: fitfolio-backend
      # DATABASE_URL: postgresql://...  # point to your prod/preview DB
    ports:
      - "8081:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12

  frontend:
    image: fitfolio-frontend:prod
    container_name: fitfolio-frontend-prod
    ports:
      - "8082:80"

  db:
    image: postgres:16
    container_name: fitfolio-db-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
