"""add email verification support

Revision ID: 488ee27f900f
Revises: 8aa1267b949c
Create Date: 2025-10-28 21:59:54.707976

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "488ee27f900f"
down_revision: str | Sequence[str] | None = "8aa1267b949c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "magic_link_tokens",
        sa.Column(
            "purpose",
            sa.String(length=20),
            server_default=sa.text("'login'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_verified")
    op.drop_column("magic_link_tokens", "purpose")
    # ### end Alembic commands ###
